### ISSUE TITLE
Task 'assembleRelease' not found in root project 'application icon'. #6

### ISSUE THREAD

**Issue by pierre-gancel** [ueman/application_icon#5]
I get this issue when using another lib built on top of application_icon,
see : https://github.com/Apparence-io/pal-plugin/issues/6

It is indeed probably coming from a default in my config,
Would you have a trick to avoid this null issue ?
I tried to pass it an empty Drawable to make peace, but that compiler will have non of it

.pub-cache/hosted/pub.dartlang.org/application_icon-1.0.0/android/src/main/kotlin/de/ju/application_icon/AppIconLoader.kt:
(71, 16): Type mismatch: inferred type is Drawable? but Drawable was expected

<img width="1110" alt="z" src="https://user-images.githubusercontent.com/69810198/106629505-333dc100-657b-11eb-99cc-227c27e38f19.png">

**Comment by ueman** [comment]
I will take look in the next few days. 
Could you provide the output of `flutter doctor -v`? By doing so I will know your environment which hopefully helps to find the bug quicker.

**Comment by pierre-gancel** [comment]
Thanks Ueman for the super quick reply.
Here goes : 

> [✓] Flutter (Channel dev, 1.26.0-12.0.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
>     • Flutter version 1.26.0-12.0.pre at /Users/pierre/flutter
>     • Framework revision a706cd2112 (3 weeks ago), 2021-01-14 18:20:26 -0500
>     • Engine revision effb529ece
>     • Dart version 2.12.0 (build 2.12.0-224.0.dev)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/pierre/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.0
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.52.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.19.0
> 
> [✓] Connected device (4 available)
>     • SM G920F (mobile)      • 0815f8aac13f2d04 • android-arm64  • Android 7.0 (API 24)
>     • Redmi Note 9S (mobile) • e2a4102e         • android-arm64  • Android 10 (API 29)
>     • macOS (desktop)        • macos            • darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
>     • Chrome (web)           • chrome           • web-javascript • Google Chrome 88.0.4324.96

**Comment by ueman** [comment]
Okay, so I see you are using the Flutter beta channel. This package isn't testet on it and isn't yet migrated to nullsafety. So that could already be the problem. I'll have to test that.

Have you tried building it on the stable channel?

**Comment by pierre-gancel** [comment]
Hi @ueman,

Thank you again for quick reply,
Yes I did try on stable,
This is the new flutter doctor

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/pierre/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pierre/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • SM G920F (mobile) • 0815f8aac13f2d04 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

**Comment by ueman** [comment]
Thanks!

**Comment by ueman** [comment]
I've just published a new version which fixes this issue.
See https://pub.dev/packages/application_icon/changelog

**Comment by pierre-gancel** [comment]
Thanks a lot :)
